// Inline style objects for the booking app.
// Kept as a single object so consumers can call `s.foo`.

export const s = {
  page:{maxWidth:1200,margin:'0 auto',padding:'1.5rem 1rem',fontFamily:"'Avenir Next','Avenir','Century Gothic','Nunito','system-ui',sans-serif",color:'#1a1a18',position:'relative',minHeight:'100vh'},
  loading:{padding:'3rem',textAlign:'center',color:'#888',fontFamily:"'Avenir Next','Avenir','Century Gothic','Nunito','system-ui',sans-serif"},
  header:{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:'1.5rem',flexWrap:'wrap',gap:10},
  headerLeft:{display:'flex',alignItems:'center',gap:14},
  headerRight:{display:'flex',alignItems:'center',gap:8,flexWrap:'wrap'},
  brandLogo:{width:44,height:44,objectFit:'contain',flexShrink:0},
  brand:{fontSize:11,fontWeight:700,color:'#1B3A78',letterSpacing:'0.12em',textTransform:'uppercase'},
  title:{fontSize:20,fontWeight:600,margin:0,color:'#1a1a18',letterSpacing:'-0.01em'},
  addBtn:{padding:'7px 14px',fontSize:13,borderRadius:8,border:'0.5px solid #d0cfc8',background:'#fff',color:'#1a1a18',cursor:'pointer',fontFamily:'inherit',whiteSpace:'nowrap'},
  menuItem:{display:'block',width:'100%',padding:'11px 16px',fontSize:14,fontWeight:500,border:'none',background:'none',color:'#1A1B2E',cursor:'pointer',textAlign:'left',fontFamily:'inherit'},
  logoutBtn:{padding:'7px 14px',fontSize:13,borderRadius:8,border:'0.5px solid #d0cfc8',background:'none',color:'#888',cursor:'pointer',fontFamily:'inherit'},
  tabs:{display:'flex',gap:4,background:'#f1f0ea',borderRadius:8,padding:4},
  tab:{padding:'6px 14px',fontSize:13,border:'none',background:'transparent',color:'#888',borderRadius:6,cursor:'pointer',fontFamily:'inherit'},
  tabActive:{background:'#fff',color:'#1a1a18',border:'0.5px solid #d0cfc8'},
  filterBar:{display:'flex',gap:8,flexWrap:'wrap',marginBottom:'0.5rem',alignItems:'center'},
  filterInfo:{fontSize:12,color:'#555',marginBottom:'0.75rem',padding:'6px 10px',background:'#f0f7ff',borderRadius:6},
  select:{fontSize:13,padding:'6px 10px',borderRadius:8,border:'0.5px solid #d0cfc8',background:'#fff',color:'#1a1a18',fontFamily:'inherit'},
  search:{fontSize:13,padding:'6px 10px',borderRadius:8,border:'0.5px solid #d0cfc8',background:'#fff',color:'#1a1a18',fontFamily:'inherit',minWidth:160},
  clearBtn:{fontSize:12,color:'#888',background:'none',border:'none',cursor:'pointer',fontFamily:'inherit',padding:'4px 6px'},
  weekNav:{display:'flex',alignItems:'center',gap:10,marginBottom:'.75rem'},
  navBtn:{background:'none',border:'0.5px solid #d0cfc8',borderRadius:8,padding:'5px 10px',cursor:'pointer',fontSize:13,color:'#1a1a18',fontFamily:'inherit'},
  weekLabel:{fontSize:13,color:'#888'},
  legend:{display:'flex',gap:14,flexWrap:'wrap',marginBottom:'.75rem'},
  legendItem:{display:'flex',alignItems:'center',gap:6,fontSize:12,color:'#888'},
  dot:{width:10,height:10,borderRadius:'50%',display:'inline-block'},
  tableWrap:{overflowX:'auto'},
  table:{width:'100%',borderCollapse:'collapse',fontSize:13,minWidth:580},
  th:{padding:'8px 6px',fontWeight:500,color:'#888',textAlign:'center',fontSize:11,borderBottom:'0.5px solid #e0dfd8'},
  crewCell:{padding:'8px 10px',borderBottom:'0.5px solid #e0dfd8',whiteSpace:'nowrap'},
  crewInfo:{display:'flex',alignItems:'center',gap:8,cursor:'pointer'},
  avatar:{width:30,height:30,borderRadius:'50%',display:'flex',alignItems:'center',justifyContent:'center',fontSize:11,fontWeight:500,flexShrink:0},
  crewName:{fontSize:13,fontWeight:500,color:'#1a1a18'},
  dayCell:{padding:'8px 6px',textAlign:'center',borderBottom:'0.5px solid #e0dfd8',borderLeft:'0.5px solid #e0dfd8',minWidth:110,verticalAlign:'top'},
  pill:{display:'inline-flex',alignItems:'center',justifyContent:'center',width:32,height:32,borderRadius:'50%',fontSize:11,cursor:'pointer',fontWeight:500,border:'none',fontFamily:'inherit'},
  projectLabel:{fontSize:10,color:'#444',lineHeight:1.4,marginTop:2,wordBreak:'break-word',maxWidth:100,textAlign:'center'},
  bookedByLabel:{fontSize:9,color:'#aaa',lineHeight:1.3,textAlign:'center'},
  crewGrid:{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(200px,1fr))',gap:12},
  crewCard:{background:'#fff',borderRadius:12,border:'0.5px solid #e0dfd8',padding:'1.25rem',cursor:'pointer'},
  rate:{fontSize:20,fontWeight:500,color:'#1a1a18'},
  rateUnit:{fontSize:12,fontWeight:400,color:'#888'},
  skillTag:{background:'#f5f4f0',border:'0.5px solid #e0dfd8',borderRadius:20,padding:'3px 8px',fontSize:11,color:'#1a1a18'},
  overlay:{position:'fixed',inset:0,background:'rgba(0,0,0,0.35)',zIndex:100,display:'flex',alignItems:'flex-start',justifyContent:'center',paddingTop:'2rem'},
  modal:{background:'#fff',borderRadius:16,border:'0.5px solid #e0dfd8',padding:'1.5rem',width:'100%',maxWidth:480,position:'relative',maxHeight:'85vh',overflowY:'auto',margin:'0 1rem'},
  closeBtn:{position:'absolute',top:12,right:12,background:'none',border:'none',fontSize:18,cursor:'pointer',color:'#888',fontFamily:'inherit'},
  editBtn:{fontSize:11,color:'#666',background:'none',border:'0.5px solid #d0cfc8',borderRadius:6,padding:'3px 8px',cursor:'pointer',fontFamily:'inherit'},
  modalAvatar:{width:56,height:56,borderRadius:'50%',display:'flex',alignItems:'center',justifyContent:'center',fontSize:18,fontWeight:500,marginBottom:10},
  infoGrid:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginTop:'1.1rem'},
  infoCell:{background:'#f5f4f0',borderRadius:8,padding:'10px 12px'},
  statsGrid:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:'1.1rem'},
  statCard:{background:'#f5f4f0',borderRadius:8,padding:'10px 12px'},
  statLabel:{fontSize:11,color:'#888',marginBottom:3},
  statVal:{fontSize:16,fontWeight:500,color:'#1a1a18'},
  msec:{marginTop:0,paddingTop:'1rem',borderTop:'1px solid #f0f0ea'},
  msecHdr:{fontSize:12,fontWeight:700,color:'#1a1a18',textTransform:'uppercase',letterSpacing:'.06em',marginBottom:6},
  bookingRow:{display:'flex',alignItems:'center',gap:8,padding:'5px 0',borderBottom:'0.5px solid #e0dfd8',fontSize:13},
  bookingDay:{color:'#888',minWidth:80,fontSize:12},
  bookingProject:{fontWeight:500,color:'#1a1a18',flex:1},
  bookingBy:{fontSize:11,color:'#aaa'},
  skillRow:{display:'flex',alignItems:'center',gap:8,padding:'6px 0',borderBottom:'0.5px solid #e0dfd8'},
  skillName:{fontSize:13,fontWeight:500,color:'#1a1a18',minWidth:110},
  comment:{flex:1,fontSize:12,color:'#444',lineHeight:1.5,cursor:'pointer',padding:'2px 4px',borderRadius:4},
  commentEmpty:{color:'#aaa',fontStyle:'italic'},
  commentInput:{flex:1,fontSize:12,padding:'4px 8px',borderRadius:6,border:'0.5px solid #b0afaa',background:'#fff',color:'#1a1a18',fontFamily:'inherit',outline:'none'},
  delSkill:{background:'none',border:'none',cursor:'pointer',color:'#aaa',fontSize:13,padding:'2px 4px',lineHeight:1,fontFamily:'inherit',flexShrink:0},
  miniBtn:{padding:'5px 10px',fontSize:12,borderRadius:8,border:'0.5px solid #d0cfc8',background:'#fff',color:'#1a1a18',cursor:'pointer',fontFamily:'inherit',whiteSpace:'nowrap'},
  statusOpt:{padding:'10px 12px',borderRadius:8,border:'0.5px solid #d0cfc8',cursor:'pointer',display:'flex',alignItems:'center',gap:10,background:'none',textAlign:'left',fontFamily:'inherit',fontSize:13,color:'#1a1a18',width:'100%',marginBottom:6},
  formRow2:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginBottom:14},
  formLabel:{display:'block',fontSize:12,fontWeight:500,color:'#666',marginBottom:5},
  formInput:{width:'100%',padding:'8px 10px',fontSize:13,borderRadius:8,border:'0.5px solid #d0cfc8',background:'#fff',color:'#1a1a18',fontFamily:'inherit',boxSizing:'border-box'},
  submitBtn:{width:'100%',padding:10,fontSize:14,borderRadius:8,border:'none',background:'linear-gradient(135deg,#1B3A78,#3D9CBA)',color:'#fff',cursor:'pointer',fontFamily:'inherit',fontWeight:600,marginTop:4,boxShadow:'0 2px 6px rgba(27,58,120,0.25)'},
  empty:{padding:'2rem',textAlign:'center',color:'#888',fontSize:13},
  toast:{position:'fixed',bottom:'1.5rem',left:'50%',transform:'translateX(-50%)',background:'#fff',border:'0.5px solid #d0cfc8',borderRadius:8,padding:'8px 16px',fontSize:13,color:'#1a1a18',zIndex:300,whiteSpace:'nowrap'},
}
